source("model/helpers/run_wrappers.R")
source("model/helpers/output_formatters.R")
lapply(list.files("model/helpers", pattern = "_helpers\\.R$", full.names = TRUE), source) 
lapply(list.files("model/modules", pattern = "^module_.*\\.R$", full.names = TRUE), source)
lapply(list.files("model/config", pattern = "_config\\.R$", full.names = TRUE), source)
