source("gram_model/gram_helpers/run_wrappers.R")
source("gram_model/gram_helpers/output_formatters.R")
lapply(list.files("gram_model/gram_helpers", pattern = "_helpers\\.R$", full.names = TRUE), source) 
lapply(list.files("gram_model/gram_modules", pattern = "^module_.*\\.R$", full.names = TRUE), source)
lapply(list.files("gram_model/gram_config", pattern = "_config\\.R$", full.names = TRUE), source)
