---
title: "GRAM-US PAPER 2: SCREENING FOR COGNITIVE IMPAIRMENT"
output: html_notebook
---

```{r setup-global, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, echo = FALSE)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

```

```{r setup, include = FALSE}
source("gram_model/gram_setup.r")
source("gram_model/gram_simulation.r")
source("gram_calibration/gram_benchmarking_helpers.r")
source("gram_model/gram_helpers/source_all.r")
library(tableone)
sample1 <- readRDS("gram_data/acs_data/acs_age50.rds")
```


```{r load configs}
setwd(dirname(dirname(dirname(getwd()))))
scenario_files <- list.files("gram_model/gram_config/bha_scenarios", full.names = TRUE, pattern = "\\.R$")




```


```{r compute_results helper}
compute_results <- function(inputs, scenario) {
  map_dfr(50:100, function(age) {
    testperf <- f.analyze_test_performance(scenario, age - 50 + 1)
    tibble(
      Scenario = inputs[["scenario"]][["scenario"]],
      Age = age,
      N_Tests = testperf$total_tests,
      TP = sum(testperf$concordance_table[c("mci","dem"), "BHApos"]),
      FN = sum(testperf$concordance_table[c("mci","dem"), "BHAneg"]),
      TN = sum(testperf$concordance_table[c("h","tci"), "BHAneg"]),
      FP = sum(testperf$concordance_table[c("h","tci"), "BHApos"]),
      FN_All = sum(testperf$concordance_table[c("mci","dem"), c("BHAneg","NoTest")]),
      TN_All = sum(testperf$concordance_table[c("h","tci"), c("BHAneg","NoTest")]),
      PPV = round(testperf$ppv, 3),
      NPV_Test = round(testperf$npv_test, 3),
      NPV_Strategy = round(testperf$npv_strat, 3)
    )
  })
}
```

```{r calibrate}

l.inputs <- calibrate(inputs = l.inputs, n = 1000)






l.inputs1[["scenario"]][["stop_rule"]] <- 
  function(...) {
    args <- list(...)
    TRUE == TRUE   # stop BHA if any prior positive BHA
  }
```

# Scenarios
## Scenario 1: Universal Testing
```{r universal run}
l.inputs1a <- l.inputs1
l.inputs1a[["scenario"]][["scenario"]] <- "Scenario 1a: Universal BHA, annual testing until first BHA+" 

universal1 <- f.wrap_run(l.inputs1a, microdata = sample1)

l.inputs1b <- l.inputs1
l.inputs1b[["scenario"]][["scenario"]] <- "Scenario 1b: Universal BHA, testing every year until first BHA+"
l.inputs1b[["scenario"]][["repeat_interval"]] <- 1

universal2 <- f.wrap_run(l.inputs1, microdata = sample1)



inputs_list <- list(l.inputs1a, l.inputs1b)
scenario_list <- list(universal1, universal2)

all_results <- map2_dfr(inputs_list, scenario_list, compute_results)
# flextable(all_results)

 sim <- all_results %>%
   filter(Age == 70)

 
 pv_results <- all_results %>%
  pivot_longer(cols = c(PPV, NPV_Test, NPV_Strategy), names_to = "Metric", values_to = "Value") %>%
  select(Scenario, Age, Metric, Value) 

fig_results <- ggplot(data = pv_results, aes(x = Age, y = Value, color = Scenario)) +
  geom_smooth(aes(linetype = Scenario)) + 
  # scale_color_manual(values = c("darkgray","orange","darkred")) +
  # scale_linetype_manual(values = c("dotted", "dashed", "solid")) +
  facet_wrap(~ Metric) +
  xlim(60,100) +
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom",
        legend.direction = "vertical")

fig_results
```

## Scenario 2: Prompted Testing
```{r prompted run}
l.inputs2 <- l.inputs1
l.inputs2[["scenario"]][["scenario"]] <- "Scenario 2: Prompted BHA"
l.inputs2[["m.cogcon"]] <- l.inputs1[["m.cogcon"]]
l.inputs2[["m.cogcon"]][ ,"h"] <- 0.07
l.inputs2[["m.cogcon"]][ ,"mci"] <- 0.70
l.inputs2[["m.cogcon"]][ ,"dem"] <- 0.95
l.inputs2[["scenario"]][["probs_cogcon"]] <- l.inputs2[["m.cogcon"]]

prompted <- f.wrap_run(l.inputs2, microdata = sample1)
```

## Scenario 3: Reactive Testing
```{r reactive run}
l.inputs3 <- l.inputs1
l.inputs3[["scenario"]][["scenario"]] <- "Scenario 3: Reactive Testing"
l.inputs3[["m.cogcon"]] <- l.inputs1[["m.cogcon"]]
l.inputs3[["m.cogcon"]][ ,"h"] <- 0.005
l.inputs3[["m.cogcon"]][ ,"mci"] <- 0.20
l.inputs3[["m.cogcon"]][ ,"dem"] <- 0.90
l.inputs3[["scenario"]][["probs_cogcon"]] <- l.inputs3[["m.cogcon"]]

reactive <- f.wrap_run(l.inputs3, microdata = sample1)
```



```{r prepare results} 
inputs_list <- list(l.inputs1a, l.inputs2, l.inputs3, l.inputs1b)
scenario_list <- list(universal1, prompted, reactive, universal2)

all_results <- map2_dfr(inputs_list, scenario_list, compute_results)
# flextable(all_results)

 sim <- all_results %>%
   filter(Age == 70)

 
 pv_results <- all_results %>%
  pivot_longer(cols = c(PPV, NPV_Test, NPV_Strat), names_to = "Metric", values_to = "Value") %>%
  select(Scenario, Age, Metric, Value) 

fig_results <- ggplot(data = pv_results, aes(x = Age, y = Value, color = Scenario)) +
  geom_smooth(aes(linetype = Scenario)) + 
  # scale_color_manual(values = c("darkgray","orange","darkred")) +
  # scale_linetype_manual(values = c("dotted", "dashed", "solid")) +
  facet_wrap(~ Metric) + 
  theme_minimal(base_size = 14) +
  theme(legend.position = "bottom",
        legend.direction = "vertical")

fig_results
```


```{r validation functions, include=FALSE}
# pull prevalence of undiagnosed for validation in Excel
get_prev_no_dx <- function(l.inputs, output) {
  n_cycles <- l.inputs[["n.cycle"]]
  prev_no_dx <- matrix(NA, nrow = n_cycles, ncol = 7, 
                       dimnames = list(NULL, c("healthy","tci", "memloss", "mci", "mil", "mod", "sev")))
  
  # Identify individuals undiagnosed in the previous cycle (cycle 2 onward)
  prior_no_dx <- rbind(NA, output[-n_cycles, "DX", ] == 0)  # Shift DX to align with previous cycle
  alive_now <- output[, "ALIVE", ] == 1  # Alive in the current cycle
  
  # Number of people alive without prior diagnosis
  n_no_dx <- rowSums(prior_no_dx & alive_now, na.rm = TRUE)
  
  # Calculate prevalence for each category
  prev_no_dx[, "healthy"] <- rowSums(output[, "SYN", ] == 0 & prior_no_dx & alive_now, na.rm = TRUE) / n_no_dx
  prev_no_dx[,"tci"] <- rowSums(output[,"SYN", ] == 0.5 & prior_no_dx & alive_now, na.rm = TRUE) / n_no_dx
  prev_no_dx[,"memloss"] <- rowSums(output[,"MEMLOSS", ] == 1 & prior_no_dx & alive_now, na.rm = TRUE) / n_no_dx
  prev_no_dx[, "mci"] <- rowSums(output[, "SEV", ] == 0 & prior_no_dx & alive_now, na.rm = TRUE) / n_no_dx
  prev_no_dx[, "mil"] <- rowSums(output[, "SEV", ] == 1 & prior_no_dx & alive_now, na.rm = TRUE) / n_no_dx
  prev_no_dx[, "mod"] <- rowSums(output[, "SEV", ] == 2 & prior_no_dx & alive_now, na.rm = TRUE) / n_no_dx
  prev_no_dx[, "sev"] <- rowSums(output[, "SEV", ] == 3 & prior_no_dx & alive_now, na.rm = TRUE) / n_no_dx
  
  prev_no_dx  <-  as.data.frame(prev_no_dx) %>%
    mutate(mci = mci - memloss)
  
  return(as.data.frame(prev_no_dx))
}

prev_no_dx_1a <- get_prev_no_dx(l.inputs1a, scenario1a$output)
rowSums(prev_no_dx_1a)
prev_no_dx_1a[21,"tci"]
prev_no_dx_1a[21,"memloss"]
prev_no_dx_1a[21,"mci"]
sum(prev_no_dx_1a[21,c("mil","mod","sev")])

```

